export const PDF_CONTENT_MAP: Record<string, string> = {
  "legal-framework-shtt": `1. Khung khổ pháp luật và các điều ước quốc tế về sở hữu trí tuệ (SHTT)
1.1. Khung khổ pháp luật về SHTT
Qua thực tiễn 20 năm thi hành, Luật SHTT đã phát huy vai trò to lớn trong việc tạo hành lang pháp lý cho các tổ chức, cá nhân xác lập, khai thác và bảo vệ quyền SHTT, tạo môi trường kinh doanh lành mạnh cho hoạt động sản xuất - kinh doanh, góp phần khuyến khích hoạt động sáng tạo, đẩy mạnh chuyển giao công nghệ, thu hút đầu tư nước ngoài, thúc đẩy sự phát triển kinh tế - xã hội của đất nước. 
Luật SHTT được Quốc hội nước Cộng hòa xã hội chủ nghĩa Việt Nam thông qua năm 2005 (Luật số 50/2005/QH11) có hiệu lực thi hành từ ngày 01/7/2006, được sửa đổi, bổ sung năm 2009 (Luật số 36/2009/QH12), năm 2019 (Luật số 42/2019/QH14), năm 2022 (Luật số 07/2022/QH15) và năm 2025 (Luật số 93/2025/QH15, Luật số 131/2025/QH15) (sau đây gọi là “Luật SHTT”) là văn bản pháp luật quan trọng, điều chỉnh các quan hệ xã hội liên quan đến loại tài sản đặc biệt – quyền SHTT. 
Thực hiện Quyết định của Thủ tướng Chính phủ về việc xây dựng các văn bản hướng dẫn thi hành Luật SHTT, các Bộ: Khoa học và Công nghệ, Văn hoá, Thể thao và Du lịch, Nông nghiệp và Môi trường đã phối hợp với các cơ quan có liên quan xây dựng các Nghị định quy định chi tiết và hướng dẫn thi hành Luật SHTT và đã được Chính phủ ban hành:
- Nghị định số 17/2023/NĐ-CP ngày 26/4/2023 của Chính phủ quy định chi tiết một số điều và biện pháp thi hành Luật SHTT về quyền tác giả, quyền liên quan (Nghị định số 17/2023/NĐ-CP);
- Nghị định số 65/2023/NĐ-CP ngày 23/8/2023 của Chính phủ quy định chi tiết một số điều và biện pháp thi hành Luật SHTT về sở hữu công nghiệp (SHCN), bảo vệ quyền SHCN, quyền đối với giống cây trồng và quản lý nhà nước về SHTT (Nghị định số 65/2023/NĐ-CP);
- Nghị định số 79/2023/NĐ-CP ngày 15/11/2023 của Chính phủ quy định chi tiết một số điều và biện pháp thi hành Luật SHTT về quyền đối với giống cây trồng (Nghị định số 79/2023/NĐ-CP);
Ngoài ra, Bộ trưởng Bộ KH&CN, Bộ trưởng Bộ Văn hóa – Thể thao - Du lịch cũng đã triển khai ban hành các văn bản hướng dẫn đối với các quy định được Luật giao bao gồm:
- Thông tư số 23/2023/TT-BKHCN ngày 30/11/2023 của Bộ trưởng Bộ KH&CN quy định chi tiết một số điều của một số điều của Luật SHTT và biện pháp thi hành Nghị định số 65/2023/NĐ-CP ngày 23/8/2023 của Chính phủ quy định chi tiết một số điều và biện pháp thi hành Luật SHTT về SHCN, bảo vệ quyền SHCN, quyền đối với giống cây trồng và quản lý nhà nước về SHTT liên quan đến thủ tục xác lập quyền SHCN và bảo đảm thông tin SHCN;
- Thông tư số 08/2023/TT-BVHTTDL ngày 02/6/2023 của Bộ trưởng Bộ Văn hoá, Thể thao và Du lịch quy định các mẫu trong hoạt động đăng ký quyền tác giả, quyền liên quan;
- Thông tư số 07/2024/TT-BVHTTDL ngày 01/10/2024 của Bộ trưởng Bộ Văn hóa, Thể thao và Du lịch quy định định mức kinh tế - kỹ thuật dịch vụ giám định, thông tin, truyền thông về quyền tác giả, quyền liên quan phục vụ công tác quản lý nhà nước.
Trong bối cảnh Việt Nam đang có những thay đổi và định hướng phát triển mạnh mẽ về khoa học, công nghệ, đổi mới sáng tạo và chuyển đổi số. Ngày 10/12/2025, Quốc hội khóa XV, Kỳ họp thứ 10 đã thông qua Luật sửa đổi, bổ sung một số điều của Luật SHTT số 131/2025/QH15 và có hiệu lực thi hành kể từ ngày 01/4/2026.
Luật số 131/2025/QH15 tiếp tục thể chế hóa đường lối, chính sách đề ra tại các văn bản gần đây của Đảng, Nhà nước bao gồm: Chiến lược phát triển kinh tế - xã hội 10 năm 2021-2030; Nghị quyết số 57-NQ/TW ngày 22/12/2024 của Bộ Chính trị về đột phá phát triển khoa học, công nghệ, đổi mới sáng tạo và chuyển đổi số quốc gia; Nghị quyết số 59-NQ/TW ngày 24/01/2025 của Bộ Chính trị về hội nhập quốc tế trong tình hình mới; Nghị quyết số 66-NQ/TW ngày 30/4/2025 của Bộ Chính trị về đổi mới công tác xây dựng và thi hành pháp luật đáp ứng yêu cầu phát triển đất nước trong kỷ nguyên mới; Nghị quyết số 68-NQ/TW ngày 04/5/2025 của Bộ Chính trị về phát triển kinh tế tư nhân; v.v.
Bên cạnh đó, việc sửa đổi, bổ sung Luật SHTT cũng cần được thực hiện để bảo đảm tính thống nhất với một loạt các văn bản quy phạm pháp luật đã được ban hành trong thời gian gần đây, đặc biệt là Luật Khoa học, công nghệ và đổi mới sáng tạo, đồng thời khắc phục một số tồn tại, hạn chế trong thực tiễn cũng như kịp thời xử lý các xu hướng mới về SHTT trên thế giới, bảo đảm tuân thủ hoàn toàn các cam kết quốc tế trong bối cảnh thực tiễn thương mại thế giới thay đổi (sự bùng nổ của thương mại điện tử), xử lý một số vấn đề đặt ra trong tình hình mới.
Những nội dung chủ yếu trong Luật sửa đổi, bổ sung một số điều của Luật SHTT:
- Cải cách thủ tục hành chính và chuyển đổi số toàn diện hoạt động SHTT
Quán triệt tinh thần của Nghị quyết 57-NQ/TW, Nghị quyết số 68-NQ/TW, Luật số 131/2025/QH15 đã rút ngắn đáng kể thời gian xử lý đơn sở hữu công nghiệp, đơn giản hóa thủ tục xác lập, đăng ký quyền, đồng thời quy định một số biện pháp để bảo đảm thực hiện các yêu cầu mới về thời hạn này, cụ thể:
Thời gian xử lý đơn SHCN ở mỗi khâu đều giảm, đáng chú ý nhất là thời hạn thẩm định nội dung đơn sáng chế đã giảm từ 18 tháng xuống còn 12 tháng, đơn nhãn hiệu giảm từ 09 tháng xuống 05 tháng, đơn kiểu dáng công nghiệp giảm từ 07 tháng xuống 05 tháng, thời gian công bố đơn giảm từ 02 tháng xuống còn 01 tháng, v.v.. Đặc biệt, Luật đã bổ sung quy định về cơ chế thẩm định nội dung nhanh đơn đăng ký sáng chế, nhãn hiệu (thẩm định nội dung trong thời hạn 03 tháng khi đáp ứng điều kiện do Chính phủ quy định). Hiện chỉ một số rất ít quốc gia có cơ chế thẩm định nội dung đơn nhanh dưới 03 tháng.
Luật yêu cầu chuyển đổi số toàn diện, đơn giản hóa quy trình xử lý đơn, tăng cường hậu kiểm, ứng dụng công nghệ mới và trí tuệ nhân tạo để thực hiện được các quy định về thời hạn trên, đồng thời nâng cao hiệu quả hoạt động SHTT.
- Thúc đẩy khai thác thương mại quyền SHTT
Luật đã quy định khung về việc hỗ trợ tạo ra và khai thác thương mại quyền SHTT nhằm biến quyền SHTT thành tài sản sinh lời, góp phần phát triển kinh tế - xã hội; quy định rõ chủ sở hữu được sử dụng quyền SHTT để thực hiện giao dịch dân sự, thương mại, đầu tư, v.v theo quy định của pháp luật cũng như chính sách khuyến khích khai thác quyền SHTT, sử dụng quyền SHTT để góp vốn hoặc thế chấp để vay vốn.
Để thúc đẩy và tạo thuận lợi cho các hoạt động khai thác thương mại quyền SHTT, Luật cũng quy định hình thành cơ sở dữ liệu giá giao dịch quyền SHTT để minh bạch thị trường, phát triển tổ chức trung gian (định giá, môi giới,), v.v.
Luật cũng đã quy định trách nhiệm lập danh mục riêng để quản trị nội bộ đối với quyền SHTT chưa đáp ứng điều kiện để ghi nhận giá trị tài sản trong sổ kế toán. Hiện nay, doanh nghiệp Việt Nam chưa có thói quen quản lý quyền SHTT như một tài sản quan trọng. Tình trạng quên không thực hiện việc duy trì hoặc gia hạn hiệu lực văn bằng bảo hộ vẫn còn khá phổ biến.
Đây là những nội dung khởi đầu của bước chuyển trọng tâm từ “bảo hộ quyền” sang “khai thác, sử dụng quyền như một tài sản có giá trị”, giảm tình trạng “bằng độc quyền để treo”, mở rộng nguồn lực cho hoạt động sản xuất, kinh doanh, phục vụ phát triển kinh tế - xã hội.
- Bảo hộ đối tượng mới
Luật SHTT đã mở rộng bảo hộ cho một số đối tượng mới, cụ thể:
(i) Bổ sung cơ chế bảo hộ kiểu dáng công nghiệp cho phần không tách rời được của sản phẩm (bảo hộ kiểu dáng công nghiệp riêng phần) và mở rộng bảo hộ kiểu dáng công nghiệp cho sản phẩm phi vật lý (ví dụ: giao diện đồ họa người dùng (GUI), icon, v.v);
(ii) Bảo hộ quyền tác giả, quyền liên quan đối với tín hiệu cáp mang chương trình được mã hóa.
- Xử lý vấn đề mới phát sinh 
Luật số 131/2025/QH15 lần này cũng đưa ra những quy định để xử lý một số vấn đề phát sinh do sự phát triển của công nghệ, nổi bật là các vấn đề liên quan đến hệ thống trí tuệ nhân tạo (AI), cụ thể:
(i) Quy định khai thác dữ liệu để nghiên cứu, thử nghiệm, huấn luyện hệ thống AI với điều kiện không ảnh hưởng bất hợp lý đến quyền và lợi ích hợp pháp của chủ sở hữu, tác giả và tuân thủ các quy định của Chính phủ; 
(ii) Quy định về vấn đề bảo hộ SHTT đối với đối tượng do AI tạo ra hoặc có sử dụng AI trong quá trình tạo ra, cụ thể là: 
+ Bổ sung quy định từ chối và hủy bỏ văn bằng bảo hộ khi phát hiện chủ thể tạo ra không phải là con người, phù hợp với chính sách chỉ bảo hộ quyền SHTT cho các đối tượng do con người tạo ra (tác giả là con người);
+ Giao Chính phủ quy định việc phát sinh, xác lập quyền SHTT đối với đối tượng quyền SHTT được tạo ra có sử dụng AI.
Bên cạnh đó, về vấn đề đăng ký nhãn hiệu chứa tên quốc gia Việt Nam, Luật cũng đã bổ sung quy định kiểm soát việc đăng ký đối với nhãn hiệu này.
- Nâng cao hiệu quả của hoạt động bảo vệ quyền SHTT
Luật bổ sung thêm các chế tài, biện pháp dân sự để xử lý hành vi xâm phạm quyền trên môi trường số, quy định rõ trách nhiệm của chủ quản nền tảng số trong việc triển khai các biện pháp bảo vệ quyền SHTT; đồng thời nâng mức bồi thường thiệt hại theo luật định để tăng tính răn đe và phù hợp với thực tiễn.`,
  "asean-treaties": `1.2.1. Các hiệp định đa phương trong khuôn khổ ASEAN
Trong phạm vi nội khối, các quốc gia thành viên ASEAN đã ký kết một số điều ước quốc tế, thỏa thuận hợp tác trong lĩnh vực SHTT, tuy nhiên nội dung của các văn bản này chủ yếu là tăng cường hoạt động hợp tác về SHTT giữa các nước thành viên, thúc đẩy phổ biến và chuyển giao công nghệ, vì lợi ích chung của Cộng đồng.
Với tư cách là thành viên ASEAN, Việt Nam cũng tham gia ký kết hiệp định thương mại hàng hóa, hiệp định thương mại dịch vụ, hiệp định thương mại đầu tư với một số quốc gia khác như Nhật Bản, Ấn Độ, Hàn Quốc, Trung Quốc, Úc và New Zealand. Tuy nhiên, ngoại trừ FTA ASEAN-Úc-New Zealand và Hiệp định RCEP là có chương riêng với các cam kết cụ thể về bảo hộ quyền SHTT, các hiệp định còn lại đều không có nội dung SHTT hoặc nếu có thì chỉ viện dẫn tới Hiệp định TRIPS của WTO.
(i) Hiệp định khung ASEAN về hợp tác SHTT
Đây là điều ước quốc tế đầu tiên về SHTT mà các quốc gia thành viên ASEAN ký kết với nhau, tạo cơ sở pháp lý cho việc hợp tác giữa các quốc gia trong lĩnh vực SHTT. Hiệp định được ký tại Bangkok (Thái Lan) vào ngày 15/12/1995 giữa 7 quốc gia thành viên là Brunei, Indonesia, Malaysia, Philippines, Singapore, Thái Lan và Việt Nam. 
Hiệp định gồm 8 điều, quy định những vấn đề cơ bản nhất về hợp tác SHTT giữa các quốc gia thành viên. Các thỏa thuận nội khối sẽ được thực hiện phù hợp với mục tiêu, nguyên tắc và chuẩn mực trong các điều ước quốc tế liên quan và Hiệp định TRIPS, tạo thuận lợi cho các nhà sáng tạo, nhà sản xuất và người sử dụng SHTT, góp phần phát triển kinh tế - xã hội. 
(ii) Hiệp định FTA ASEAN - Ấn Độ
ASEAN và Ấn Độ ký kết Hiệp định khung về Hợp tác kinh tế toàn diện ngày 8/10/2003, có hiệu lực từ ngày 01/7/2004. Trên cơ sở Hiệp định khung, các Bên tiếp tục ký kết Hiệp định về Hàng hóa (có hiệu lực từ tháng 1/2010), Hiệp định về Dịch vụ (có hiệu lực từ tháng 7/2015) và Hiệp định về Đầu tư (có hiệu lực từ tháng 7/2015) nhằm hình thành Khu vực thương mại tự do ASEAN - Ấn Độ.`,
  "enforcement-trends": `2.3. Xu hướng vi phạm và các phương thức, thủ đoạn mới
Một trong những xu hướng nổi bật hiện nay là sự gia tăng nhanh chóng của các hành vi vi phạm trên môi trường số. Các đối tượng vi phạm đã tận dụng triệt để các nền tảng thương mại điện tử, mạng xã hội và công nghệ số để triển khai hoạt động buôn bán hàng giả, hàng xâm phạm quyền với quy mô lớn nhưng phân tán, khó kiểm soát.
Đáng chú ý, các công nghệ mới như trí tuệ nhân tạo (AI) đang bị lợi dụng để phục vụ hành vi vi phạm. Các đối tượng sử dụng AI và công nghệ deepfake để tạo ra hình ảnh, video quảng cáo giả mạo, có dấu hiệu tương tự với nhãn hiệu được bảo hộ, qua đó đánh lừa người tiêu dùng. Đồng thời, hình thức livestream bán hàng “chớp nhoáng” được tổ chức ngày càng phổ biến, với đặc điểm diễn ra trong thời gian ngắn và nhanh chóng xóa bỏ nội dung sau khi kết thúc nhằm tránh bị phát hiện, gây khó khăn cho công tác thu thập chứng cứ.
Ngoài ra, các thủ đoạn như làm giả tem truy xuất nguồn gốc, sử dụng thông tin sai lệch hoặc gây nhầm lẫn về sản phẩm ngày càng tinh vi. Hoạt động sản xuất và phân phối hàng giả được tổ chức theo mô hình khép kín, sử dụng kho hàng tạm, địa chỉ ảo và thường xuyên thay đổi địa điểm. Hàng hóa vi phạm được vận chuyển qua các hình thức tiểu ngạch hoặc bưu gửi nhỏ lẻ với tần suất lớn, gây khó khăn cho công tác kiểm soát.
Tình trạng “mập mờ” thông tin trên không gian mạng liên quan đến nguồn gốc, chất lượng sản phẩm và quyền SHTT đang trở thành vấn đề nổi cộm, ảnh hưởng trực tiếp đến quyền lợi người tiêu dùng và môi trường cạnh tranh lành mạnh.`
};
